#!/bin/sh
# Arch install script with my favourite choices

# Add aur function
source ./install/aur

echo "LOADING INSTALL VARIABLES..."
source ./install/vars

echo "HARDDISK SETUP..."
# source ./install/disk

echo "INSTALLING BASE SYSTEM..."
source ./install/base

echo "CONFIGURING LOCALES..."
source ./install/locales

echo "BOOTLOADER SETUP..."
source ./install/bootloader

echo "ADDING USERS..."
source ./install/users

echo "WIFI SETUP..."
source ./install/wifi

echo "INSTALLING SESSION FILES..."
source ./install/session

echo "INSTALLING HYPRLAND WM..."
source ./install/hyprland

echo "AUDIO SETUP..."
source ./install/audio

echo "INSTALLING ADITIONAL FONTS..."
source ./install/fonts

echo "INSTALLING APPLICATIONS..."
source ./install/apps

echo "INSTALLING WINDOWS EMULATOR (WINE)..."
source ./install/wine

echo "AUTOFS SETUP..."
source ./install/autofs

echo "COPYING HELPER SCRIPTS TO /usr/local/bin..."
cp -v scripts/* /usr/local/bin

echo "DONE!"

