#!/bin/sh
# Arch install script with my favourite choices

show_title() {
  echo "------------------------------------------------------------------" 
  echo $1
  echo "------------------------------------------------------------------"
}

# Add aur function
source ./install/aur

show_title "LOADING INSTALL VARIABLES..."
source ./install/vars

show_title "HARDDISK SETUP..."
# source ./install/disk

show_title "INSTALLING BASE SYSTEM..."
source ./install/base

show_title "CONFIGURING LOCALES..."
source ./install/locales

show_title "BOOTLOADER SETUP..."
source ./install/bootloader

show_title "ADDING USERS..."
source ./install/users

show_title "WIFI SETUP..."
source ./install/wifi

show_title "INSTALLING SESSION FILES..."
source ./install/session

show_title "INSTALLING HYPRLAND WM..."
source ./install/hyprland

show_title "AUDIO SETUP..."
source ./install/audio

show_title "INSTALLING ADITIONAL FONTS..."
source ./install/fonts

show_title  "INSTALLING APPLICATIONS..."
source ./install/apps

show_title "INSTALLING WINDOWS EMULATOR (WINE)..."
source ./install/wine

show_title "AUTOFS SETUP..."
source ./install/autofs

show_title "COPYING HELPER SCRIPTS TO /usr/local/bin..."
cp -v scripts/* /usr/local/bin

echo "DONE!"

