#!/bin/sh
# Arch install script with my favourite choices

source ./install/vars

# source ./install/disk

source ./install/base
source ./install/locales

# source ./install/bootloader
#users
#enable_services
#wifi
#yay
#session
#hyprland
#audio
#fonts
#apps
#wine
#autofs
#scripts

