#!/bin/sh

aur() {
  echo "Installing $1 from AUR..."
  mkdir -p ${BUILD_DIR}
  chown build:build ${BUILD_DIR}
  cd ${BUILD_DIR}
  sudo -u build git clone https://aur.archlinux.org/$1.git
  cd $1
  sudo -u build makepkg -s
  ${INSTALL_ZST} *.zst
  # cd ..
}
