#!/bin/sh

# alsa (audio)
${PACMAN} alsa-lib alsa-plugins alsa-tools alsa-utils alsa-firmware
gpasswd -a ${_USERNAME} audio

# pipewire (audio)
${PACMAN} pipewire pipewire-audio pipewire-alsa pipewire-pulse pipewire-jack

# openal
${PACMAN} openal realtime-privileges

# Multimedia graph framework
${PACMAN} gst-plugin-pipewire gst-plugins-base gst-plugins-bad gst-plugins-good \
  gst-plugins-ugly

${PACMAN} pavucontrol


