#!/bin/sh

${PACMAN} adobe-source-code-pro-fonts awesome-terminal-fonts cantarell-fonts \
  gnu-free-fonts noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra \
  ttf-dejavu ttf-font-awesome ttf-ionicons ttf-liberation ttf-opensans \
  ttf-sourcecodepro-nerd ttf-hack powerline-fonts ttc-iosevka

aur siji-ttf
aur ttf-font-icons
aur ttf-ms-win10-auto
aur ttf-unicons

cp -v Madness.ttf /usr/share/fonts/TTF

