#!/bin/sh

${PACMAN} base-devel gdb ninja gcc cmake libxcb xcb-proto xcb-util \
  xcb-util-keysyms libxfixes libx11 libxcomposite xorg-xinput libxrender \
  pixman wayland-protocols cairo pango seatd libxkbcommon xcb-util-wm \
  xorg-xwayland cmake wlroots mesa git meson polkit lxqt-policykit wofi \
  jq wayland-utils wdisplays

  aur hyprland-bin

  aur waybar-hyprland-git

  # Install Hyprpaper
  git clone https://github.com/hyprwm/hyprpaper  
  cd hyprpaper  
  make all  
  sudo cp build/hyprpaper /usr/local/bin 
  cd ..

  # Copy hyprland conf
  mkdir -p ${CONF_DIR}/hypr
  cp -Rv config/hypr/* ${CONF_DIR}/hypr

  # Copy waybar conf
  mkdir -p ${CONF_DIR}/waybar
  cp -Rv config/waybar/* ${CONF_DIR}/waybar

  ${PACMAN} kitty zathura openssh p7zip pop-icon-theme capitaine-cursors breeze-icons

  aur fantome-gtk
  aur nitch

  gsettings set org.gnome.desktop.interface icon-theme Pop  
  gsettings set org.gnome.desktop.interface gtk-theme Fantome
  gsettings set org.gnome.desktop.interface cursor-theme capitaine-cursors

  ${PACMAN} qt5-wayland qt5ct qt5-webchannel qt5-webengine polkit-qt5 polkit-kde-agent

