#!/bin/sh

cd ~

#export _JAVA_AWT_WM_NONREPARENTING=1
#export XCURSOR_SIZE=24
#export MOZ_ENABLE_WAYLAND=1

##export SDL_VIDEODRIVER=wayland

export GTK_THEME=Materia:light
export QT_QPA_PLATFORM=wayland

exec Hyprland &> /dev/null


