#!/bin/sh

echo "Set root password:"
passwd

useradd -m -g users -G wheel -s /bin/zsh ${_USERNAME}
echo "Set password for user ${_USERNAME}:"
passwd ${_USERNAME}

# Add group wheel to sudoers
sed 's/# %wheel/%wheel/g' /etc/sudoers
