#!/bin/sh

# iwd (wifi)

${PACMAN} iwd

echo "[Security]
EAP-Method=PEAP
EAP-Identity=${EAP_IDENTITY}
EAP-PEAP-Phase2-Method=MSCHAPV2
EAP-PEAP-Phase2-Identity=${EAP_IDENTITY}
EAP-PEAP-Phase2-Password=${EAP_PASSWORD}
[Settings]
AutoConnect=true" > /var/lib/iwd/gencat_ENS_EDU.8021x

systemctl enable iwd

